@@ -1,19 +1,18 @@
my:	my:
  greeting: Hello Midway	  greeting: Hello Midway
  list:	  list:
          values: One, Two, Three, Four, Five, Six, Seven	          values: One, Two, Three, Four, Five, Six, Seven
db:	db:
  connection: connection-string-here	  connection: connection-string-here
  host: 127.0.0.1	  host: 127.0.0.1
  port: 1200	  port: 1200


ROLES:	ROLES:
  topaz:	  - url: /topaz/conta-corrente/debito
    - url: /topaz/conta-corrente/debito	  - role1: ROLE_TOPAS_DEBITO_CONTA
    - role: ROLE_TOPAS_DEBITO_CONTA	  - role2: ROLE_TOPAS_INSERT
    - role: ROLE_TOPAS_INSERT	  - role3: ROLE_TOPAS_DELETE
    - role: ROLE_TOPAS_DELETE	  - role4: ROLE_TOPAS_UPDATE
    - role: ROLE_TOPAS_UPDATE	


ROLES_URLS:	ROLES_URLS:
  topaz:	  topaz:
   - url: /topaz/conta-corrente/debito	   - url: /topaz/conta-corrente/debito
   - url: /topaz/conta-corrente/credito
