my:
  greeting: Hello Midway
  list:
          values: One, Two, Three, Four, Five, Six, Seven
db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200
  
ROLES:
  topaz:
    url: /topaz/conta-corrente/debito
    role: ROLE_TOPAS_DEBITO_CONTA
  
  matera:
    url: /topaz/conta-corrente/credito
    role: ROLE_TOPAS_CREDITO_CONTA



  
