my:
  greeting: Hello Midway
  list:
          values: One, Two, Three, Four, Five, Six, Seven
db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200
  
ROUTERS:
  url: /topaz/conta-corrente/debito
  role: ROLE_TOPAS_DEBITO_CONTA

ROUTERS:
  url: /topaz/conta-corrente/credito
  role: ROLE_TOPAS_CREDITO_CONTA

  
