my:
  greeting: Hello Midway	
  list:	  list:
          values: One, Two, Three, Four, Five, Six, Seven
db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200


ROLES:
  topaz:	
    - role: ROLE_TOPAS_DEBITO_CONTA
    - role: ROLE_TOPAS_INSERT
    - role: ROLE_TOPAS_DELETE
    - role: ROLE_TOPAS_UPDATE	


ROLES_URLS:
  topaz:
   - url: /topaz/conta-corrente/debito
   - url: /topaz/conta-corrente/credito
